trigger:
- none

pool:
  vmImage: ubuntu-latest

stages:
  - stage: tfvalidate
    jobs:
      - job: validate
        continueOnError: false
        steps:
          - task: TerraformInstaller@1
            displayName: install
            inputs:
              terraformVersion: 'latest'
          - task: TerraformTaskV4@4
            displayName: init
            inputs:
              provider: 'azurerm'
              command: 'init'
              backendServiceArm: 'proj10srvconn10'
              backendAzureRmResourceGroupName: 'MKSRGTerraAzSub1'
              backendAzureRmStorageAccountName: 'mksterrastoreazsub1'
              backendAzureRmContainerName: 'mksterracontraz1'
              backendAzureRmKey: 'mksgit1.tfstate'
          - task: TerraformTaskV4@4
            displayName: plan
            inputs:
              provider: 'azurerm'
              command: 'plan'
              environmentServiceNameAzureRM: 'proj10srvconn10'
          - task: TerraformTaskV4@4
            displayName: destroy
            inputs:
              provider: 'azurerm'
              command: 'destroy'
              environmentServiceNameAzureRM: 'proj10srvconn10'
